"""init schema

Revision ID: 70ef2a840e17
Revises: 
Create Date: 2026-01-30 07:00:46.315911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ef2a840e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('students',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('client_user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_client_user_id'), ['client_user_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PASSIVE', name='enrollmentstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_user_id', 'student_id', name='uq_teacher_student')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_teacher_user_id'), ['teacher_user_id'], unique=False)

    op.create_table('lesson_sessions',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('ONLINE', 'IN_PERSON', name='sessionmode'), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'PENDING_CONFIRMATION', 'COMPLETED', 'CANCELLED', 'MISSED', name='sessionstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('teacher_rating_to_student', sa.Integer(), nullable=True),
    sa.Column('teacher_mark_note', sa.Text(), nullable=True),
    sa.Column('teacher_marked_at', sa.DateTime(), nullable=True),
    sa.Column('client_rating_to_teacher', sa.Integer(), nullable=True),
    sa.Column('client_note', sa.Text(), nullable=True),
    sa.Column('client_marked_at', sa.DateTime(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('client_rating_to_teacher BETWEEN 1 AND 5', name='ck_client_rating_1_5'),
    sa.CheckConstraint('teacher_rating_to_student BETWEEN 1 AND 5', name='ck_teacher_rating_1_5'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_sessions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_sessions_scheduled_start'), ['scheduled_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_sessions_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_sessions_teacher_user_id'), ['teacher_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_sessions_teacher_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_sessions_student_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_sessions_scheduled_start'))
        batch_op.drop_index(batch_op.f('ix_lesson_sessions_created_by_user_id'))

    op.drop_table('lesson_sessions')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_teacher_user_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_client_user_id'))

    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
