"""add profiles reports homeworks packages

Revision ID: c5fb4e8fd540
Revises: f1e2de57782e
Create Date: 2026-02-04 11:24:35.896934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5fb4e8fd540'
down_revision = 'f1e2de57782e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expires_in_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homeworks',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'SUBMITTED', 'GRADED', name='homeworkstatus'), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('student_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homeworks_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homeworks_teacher_user_id'), ['teacher_user_id'], unique=False)

    op.create_table('student_packages',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('remaining_lessons', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'USED_UP', name='packagestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_packages_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_packages_student_id'), ['student_id'], unique=False)

    op.create_table('lesson_reports',
    sa.Column('lesson_session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=True),
    sa.Column('performance_rating', sa.Integer(), nullable=True),
    sa.Column('teacher_note', sa.Text(), nullable=True),
    sa.Column('next_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_session_id'], ['lesson_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_reports_lesson_session_id'), ['lesson_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_reports_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_reports_teacher_user_id'), ['teacher_user_id'], unique=False)

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_teacher_student'), type_='unique')
        batch_op.create_unique_constraint('uq_enrollment_student', ['student_id'])

    with op.batch_alter_table('lesson_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consumed', sa.Boolean(), nullable=True, server_default=sa.text('false')))
        batch_op.alter_column('consumed', nullable=False, server_default=None)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_exam', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('weaknesses', sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_students_client_user_id'))
        batch_op.drop_constraint(batch_op.f('uq_students_user_id'), type_='unique')
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_students_user_id'), ['user_id'])
        batch_op.create_index(batch_op.f('ix_students_client_user_id'), ['user_id'], unique=False)
        batch_op.drop_column('weaknesses')
        batch_op.drop_column('strengths')
        batch_op.drop_column('target_exam')
        batch_op.drop_column('level')

    with op.batch_alter_table('lesson_sessions', schema=None) as batch_op:
        batch_op.drop_column('consumed')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_enrollment_student', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_teacher_student'), ['teacher_user_id', 'student_id'])

    with op.batch_alter_table('lesson_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_reports_teacher_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_reports_student_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_reports_lesson_session_id'))

    op.drop_table('lesson_reports')
    with op.batch_alter_table('student_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_packages_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_packages_package_id'))

    op.drop_table('student_packages')
    with op.batch_alter_table('homeworks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homeworks_teacher_user_id'))
        batch_op.drop_index(batch_op.f('ix_homeworks_student_id'))

    op.drop_table('homeworks')
    op.drop_table('packages')
    # ### end Alembic commands ###
